version: 0.2
### This buildspec file for plan and build jobservice app docker image
phases:

  build:
    commands:
      - pwd
      - ls
      - chmod 750 ./pipeLineScripts/runDocker.sh
      - ./pipeLineScripts/runDocker.sh 
  post_build:
    commands:
      - echo Build completed on `date`
      - chmod 750 ./pipeLineScripts/postBuild.sh
      - ./pipeLineScripts/postBuild.sh
artifacts:
  files: 
    - imageDetail.json
    - taskdef.json
    - appspec.yml
